name: Testing Secret Display

on: [push]

jobs:
  test-job:
    
    runs-on: ubuntu-latest
    container: $DOCKER_PY_VER

    steps:
    
    - name: checkout repo
      uses: actions/checkout@v2
            
    - name: use vars 
      run: |
        PY_VER="${{ $secrets.PYTHON_VERSION }}"
        DOCKER_PY_VER="${{ secrets.DOCKER_PYTHON_VERSION }}"
       
    - name: using python
      uses: actions/setup-python@v2
      with:
        python-version: $PY_VER
