name: Test for secrets display error

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: ${{ secrets.DOCKER_PYTHON_VERSION }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ secrets.PYTHON_VERSION }}
