name: Test for secrets display error

on: [push]

jobs:
  test:
    env:
      DOCKER_PYTHON_VERSION: ${{ secrets.DOCKER_PYTHON_VERSION }}
      PYTHON_VERSION: ${{ secrets.PYTHON_VERSION }}
    
    name: create python container
    runs-on: ubuntu-latest
    container: 
      image: ${{ env.DOCKER_PYTHON_VERSION }}

    steps:
    
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
