name: Testing Secret Display

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: "${ secrets.DOCKER_PYTHON_VERSION }"

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "${ secrets.PYTHON_VERSION }"
        
    - name: show vars output
      run: |
        echo "${ secrets.DOCKER_PYTHON_VERSION }"
        echo "${ secrets.PYTHON_VERSION }"
